import { Inter } from "next/font/google";
import "./globals.css";
import { Knock } from "@knocklabs/node";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const userId = "user-123";

const knockClient = new Knock(process.env.KNOCK_SECRETE_API_KEY);
const knockUser = await knockClient.users.identify(userId, {
  name: "Kongden",
  email: "doeunkongden@gmail.com"
})

console.log("Knock User :", knockUser);

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
